version: "3.9"
services:
  webapp:
    build: .
    ports:
      - 80
      - 443
    environment:
      - ConnectionStrings__LoanDatabase=Host=postgres:5432;Database=loan_los;Username=postgres;Password=postgres
      - AppEnv__UploadDestinationDirname=upload
      - AppEnv__JwtValidAudiences__0=http://localhost:5617
      - AppEnv__JwtValidAudiences__1=https://localhost:44398
      - AppEnv__JwtValidAudiences__2=https://localhost:7103
      - AppEnv__JwtValidAudiences__3=http://localhost:5268
      - AppEnv__JwtValidIssuer=local-auth
      - AppEnv__JwtIssuerSigningKey=UHzrGH2LmkcMixaAB+MSJnKud4Bkbjor1yiaxnB8yT8=
    depends_on:
      - postgres 
  postgres:
    image: "postgres:15.2"
    ports:
      - 5432
    environment:
      - POSTGRES_DB=loan_los
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
